# This is a basic workflow to help you get started with Actions

name: CCM Post Refresh Steps

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      sandbox:
        type: environment

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ccm-post-refresh:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.sandbox }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      - name: INSTALL SFDX 
        run: npm install sfdx-cli --global

      - name: AUTHENTICATE Sandbox
        shell: pwsh
        run: ../views-post-refresh/.github/workflows/authenticate-salesforce-authurl.ps1  -auth_url ${{ secrets.AUTH_URL}}  -devhub_alias ${{ secrets.ALIAS}} 

      # Runs a single command using the runners shell
      - name: RUN CCM POST-REFRESH STEPS
        shell: pwsh
        run: ../views-post-refresh/CCM/ccm-post-refresh.ps1 -auth_url ${{ secrets.AUTH_URL}} -username ${{ secrets.USERNAME}} -devhub_alias ${{ secrets.ALIAS}} 
