# This is a basic workflow to help you get started with Actions

name: FOM Post Refresh Steps

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      sandbox:
        type: environment

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # # This workflow contains a single job called "build"
  # deactivate-flows:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest
  #   environment: ${{ github.event.inputs.sandbox }}

  #   steps:

  #     # Checks-out repository under $GITHUB_WORKSPACE
  #     - uses: actions/checkout@v3
        
  #     - name: INSTALL SFDX 
  #       run: npm install sfdx-cli --global

  #     - name: AUTHENTICATE Sandbox
  #       shell: pwsh
  #       run: ../views-post-refresh/.github/workflows/authenticate-salesforce-authurl.ps1  -auth_url ${{ secrets.AUTH_URL}}  -org_alias ${{ secrets.ALIAS}} 

  #     - name: Set Default Org 
  #       run: sfdx config:set defaultusername=${{ secrets.USERNAME}} --global

  #     - name: DEACTIVATE FLOWS
  #       shell: pwsh
  #       run: |
  #         $ErrorActionPreference = 'stop'
  #         ../views-post-refresh/FOM/deactivate-flows.ps1 -username ${{ secrets.USERNAME}}



  reactivate-flows:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.sandbox }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
        
      - name: INSTALL SFDX 
        run: npm install sfdx-cli --global

      - name: AUTHENTICATE Sandbox
        shell: pwsh
        run: ../views-post-refresh/.github/workflows/authenticate-salesforce-authurl.ps1  -auth_url ${{ secrets.AUTH_URL}}  -org_alias ${{ secrets.ALIAS}} 

      - name: Set Default Org 
        run: sfdx config:set defaultusername=${{ secrets.USERNAME}} --global

      - name: REACTIVATE FLOWS
        shell: pwsh
        run: |
          $ErrorActionPreference = 'stop'
          ../views-post-refresh/FOM/reactivate-flows.ps1 -username ${{ secrets.USERNAME}}