# This is a basic workflow to help you get started with Actions

name: GAO Post Refresh Steps

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      sandbox:
        type: environment

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  gao-post-refresh:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.sandbox }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      - name: INSTALL SFDX 
        run: npm install sfdx-cli --global

      - name: AUTHENTICATE Sandbox
        shell: pwsh
        run: ../views-post-refresh/.github/workflows/authenticate-salesforce-authurl.ps1  -auth_url ${{ secrets.AUTH_URL}}  -org_alias ${{ secrets.ALIAS}} 

      - name: Set Default Org 
        shell: pwsh
        run: sfdx config:set defaultusername=${{ secrets.USERNAME}} --global

      # Runs a single command using the runners shell
      - name: UPDATE SPRINGCM Folder Path Custom Setting
        shell: pwsh
        run: |
          sfdx force:data:record:update -s SpringCM_Folder_Paths__c -w "Application_Name__c='Views_GAO_Case_Attachments'" -v "VIEWS_GAO_CASE_TASK_ATTACHMENTS_URL__C='${{ secrets.GAO_CASE_ATTACHMENTS_URL}}'"  -u ${{ secrets.USERNAME}}
          sfdx force:data:record:update -s SpringCM_Folder_Paths__c -w "Application_Name__c='Views_GAO_Case_Attachments'" -v "Folder_Path__c='Other Sources/Salesforce/Veteran Affairs/Cases'" -u ${{ secrets.USERNAME}}
          
          sfdx force:data:record:update -s SpringCM_Folder_Paths__c -w "Application_Name__c='Views_GAO_Case_Task_Attachments'" -v "VIEWS_GAO_CASE_TASK_ATTACHMENTS_URL__C='${{ secrets.GAO_CASE_TASK_ATTACHMENTS_URL}}'" -u ${{ secrets.USERNAME}}
          sfdx force:data:record:update -s SpringCM_Folder_Paths__c -w "Application_Name__c='Views_GAO_Case_Task_Attachments'" -v "Folder_Path__c='Other Sources/Salesforce/Veteran Affairs/Views Case Tasks'" -u ${{ secrets.USERNAME}}

      - name: UPDATE SPRINGCM Integration Settings CUSTOM SETTING
        shell: pwsh
        run: |
          $orgId = sfdx force:org:display -u ${{ secrets.USERNAME}} | Select-String -Pattern 'Id' 
          $orgId = $orgId | Select-String -Pattern 'Client Id' -NotMatch 
          $orgId = $orgId -replace 'Id', ""
          $orgId = $orgId -replace ' ', "" 
    
          sfdx force:data:record:update -s SpringCM_Integration_Settings__c -w "Name='SpringCM Prod Settings'" -v "Client_ID__c='${{ secrets.SPRINGCM_CLIENT_ID}}'"  -u ${{ secrets.USERNAME}}
          sfdx force:data:record:update -s SpringCM_Integration_Settings__c -w "Name='SpringCM Prod Settings'" -v "Secret_ID__c='${{ secrets.SPRINGCM_SECRET_ID}}'"  -u ${{ secrets.USERNAME}}
          sfdx force:data:record:update -s SpringCM_Integration_Settings__c -w "Name='SpringCM Prod Settings'" -v "Authentication_Service__c='https://authuat.springcm.com'" -u ${{ secrets.USERNAME}}
          sfdx force:data:record:update -s SpringCM_Integration_Settings__c -w "Name='SpringCM Prod Settings'" -v "REST_API_Download_Endpoint__c='https://apidownloaduatna11.springcm.com'" -u ${{ secrets.USERNAME}}
          sfdx force:data:record:update -s SpringCM_Integration_Settings__c -w "Name='SpringCM Prod Settings'" -v "REST_API_Upload_Endpoint__c='https://apiuploaduatna11.springcm.com'" -u ${{ secrets.USERNAME}}
          sfdx force:data:record:update -s SpringCM_Integration_Settings__c -w "Name='SpringCM Prod Settings'" -v "REST_API_Object_Endpoint__c='https://apiuatna11.springcm.com'" -u ${{ secrets.USERNAME}}
          sfdx force:data:record:update -s SpringCM_Integration_Settings__c -w "Name='SpringCM Prod Settings'" -v "Salesforce_Partner_WSDL_SOAP_endpoint__c='https://va--${{ secrets.ALIAS}}.my.salesforce.com/services/Soap/u/44.0/$test'" -u ${{ secrets.USERNAME}}
          sfdx force:data:record:update -s SpringCM_Integration_Settings__c -w "Name='SpringCM Prod Settings'" -v "Name='SpringCM ${{ secrets.ALIAS}} Settings'" -u ${{ secrets.USERNAME}}

      - name: User Setup
        shell: pwsh
        run: |
          $ErrorActionPreference = 'stop'
          Add-Content -Path temp-create-users.apex -Value "String environmentName = '${{ secrets.ALIAS}}';" 
          Add-Content -Path temp-create-users.apex (Get-Content "../views-post-refresh/GAO/apex/GAO_INT_SetupScript1_TestUsers.apex")
          sfdx force:apex:execute -f temp-create-users.apex -u ${{ secrets.USERNAME}}

      - name: Setup VA Accounts and Contacts
        shell: pwsh
        run: |
          $ErrorActionPreference = 'stop'
          Add-Content -Path temp-create-va-accounts.apex -Value "String environment = '.${{ secrets.ALIAS}}';" 
          Add-Content -Path temp-create-va-accounts.apex (Get-Content "../views-post-refresh/GAO/apex/GAO_INT_SetupScript2_TestVA_AccountsAndContacts.apex")
          sfdx force:apex:execute -f temp-create-va-accounts.apex -u ${{ secrets.USERNAME}}
 
      - name: Setup Non-VA Accounts and Contacts
        shell: pwsh
        run: |
          $ErrorActionPreference = 'stop'
          sfdx force:apex:execute -f ../views-post-refresh/GAO/apex/GAO_INT_SetupScript3_TestNonVA_AccountsAndContacts.apex -u ${{ secrets.USERNAME}}

      - name: Setup Functional Queues
        shell: pwsh
        run: |
          $ErrorActionPreference = 'stop'
          Add-Content -Path temp-create-fun-queues.apex -Value "String environment = '.${{ secrets.ALIAS}}';" 
          Add-Content -Path temp-create-fun-queues.apex (Get-Content "../views-post-refresh/GAO/apex/GAO_INT_SetupScript4_TestFunctionQueuesAndMembers.apex")
          sfdx force:apex:execute -f temp-create-fun-queues.apex -u ${{ secrets.USERNAME}}

      - name: Setup Non-VA Accounts and Contacts
        shell: pwsh
        run: |
          $ErrorActionPreference = 'stop'
          sfdx force:apex:execute -f ../views-post-refresh/GAO/apex/GAO_INT_SetupScript5_TestKWCurrentRelationhips.apex -u ${{ secrets.USERNAME}}

      - name: Setup Perm Sets
        shell: pwsh
        run: |
          $ErrorActionPreference = 'stop'
          Add-Content -Path temp-assign-permsets.apex -Value "String environment = '.${{ secrets.ALIAS}}';" 
          Add-Content -Path temp-assign-permsets.apex (Get-Content "../views-post-refresh/GAO/apex/GAO_INT_SetupScript6_TestUserPermissionSetAssignments.apex")
          sfdx force:apex:execute -f temp-assign-permsets.apex -u ${{ secrets.USERNAME}}

      - name: Setup Groups
        shell: pwsh
        run: |
          $ErrorActionPreference = 'stop'
          Add-Content -Path temp-groups.apex -Value "String environment = '.${{ secrets.ALIAS}}';" 
          Add-Content -Path temp-groups.apex (Get-Content "../views-post-refresh/GAO/apex/GAO_INT_SetupScript7_TestUserGroupMembers.apex")
          sfdx force:apex:execute -f temp-groups.apex -u ${{ secrets.USERNAME}}

      - name: Setup Non-VA Accounts and Contacts
        shell: pwsh
        run: |
          $ErrorActionPreference = 'stop'
          sfdx force:apex:execute -f ../views-post-refresh/GAO/apex/GAO_INT_SetupScript8_BatchJobScheduling.apex -u ${{ secrets.USERNAME}}
