# This is a basic workflow to help you get started with Actions

name: GAO Post Refresh Steps

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      sandbox:
        type: environment

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  gao-post-refresh:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.sandbox }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      - name: INSTALL SFDX 
        run: npm install sfdx-cli --global

      - name: AUTHENTICATE Sandbox
        shell: pwsh
        run: ../views-post-refresh/.github/workflows/authenticate-salesforce-authurl.ps1  -auth_url ${{ secrets.AUTH_URL}}  -org_alias ${{ secrets.ALIAS}} 

      - name: Set Default Org 
        shell: pwsh
        run: sfdx config:set defaultusername=${{ secrets.USERNAME}} --global

      - name: Create/Update Records
        shell: pwsh
        run: |
          $ErrorActionPreference = 'stop'
          cd ../views-post-refresh/SQUARES/data
          sfdx sfdmu:run --sourceusername csvfile --targetusername ${{ secrets.USERNAME}}
          cd ..
          cd ..
          cd ..
          
      - name: UPDATE Remote Site Settings
        shell: pwsh
        run: |
          $ErrorActionPreference = 'stop'
          sfdx force:source:deploy -m "RemoteSiteSetting:SQUARES_Adv_Veteran_Search"  -u $username
          sfdx force:source:deploy -m "RemoteSiteSetting:SQUARES_Veteran_Search"  -u $username
